server:
  port: 9892
spring:
  main:
    allow-circular-references: true
  rabbitmq:
    #host: localhost
    host: 192.168.8.60
    port: 5672
    username: admin
    password: admin
    virtual-host: test

